### PR TITLE
Pull Request: Russian Translation and fixes typos of English Translation

### PR DESCRIPTION
**Pull request by craftersmine**
I've created Russian Translation and fixed 1 misspell in English translation

Contacts (if needed):
Steam: https://steamcommunity.com/id/craftersmine/
Discord: craftersmine#7441

### CODE REVIEW

**Comment by craftersmine** [comment]
I found another misspell in English translation

**Comment by user19990313** [comment]
Accepted. This PR will be merged and released to mod sites **2 days later** in case you need to tweak the files.

Also please translate RuntimeGC.SteamWorkshopDescription.1.0.txt if you can (see issue #6). This is the Steam Workshop text and will be displayed to Spanish players (or English if not translated). Please put the translations into a separate txt file and do not modify [b][u][/i] tags or urls. Thanks!

**Comment by craftersmine** [comment]
Well, it's seems to be completely done.

**Comment by craftersmine** [comment]
Well, it took more than 2 days? Is there something wrong with the files or what?

**Comment by user19990313** [comment]
There were network issues; but now it's back to normal. Merging the PR now.

**Pull request merged**
