### PR TITLE
Pull request: Japanese Translation ver3 with Description.txt 

### PR DESCRIPTION
**Pull request by Proxyer**
- change comms console part in Keyed/HelpContents3.xml.
- add RuntimeGC.SteamWorkshopDescription.1.0_JP.txt
  The test screen when applying it is here.
  https://i.imgur.com/83LPbwT.png

### CODE REVIEW

**Comment by user19990313** [comment]
Accepted. This PR will be merged and released to mod sites **1 day later** in case you need to tweak the files.

**Comment by user19990313** [comment]
Dear Proxyer:
Please **DO NOT make DefInjections for MainButtonDef**. The def label is not translatable and the description will not be used in game, because they will be replaced by 3 keyed items which you have already translated.
I mentioned this in README:
https://github.com/user19990313/RimWorld-RuntimeGC#how-can-i-make-translation-files-for-s
Please check step 3.

If you have difficulties reading through this guide, I am considering closing this PR until you understand all the instructions.

**Comment by Proxyer** [comment]
Ok rework.

**Comment by Proxyer** [comment]
Done.
Now no MainButtonDef file.

**Pull request merged**
