### PR TITLE
Pull request: Japanese Translation for 1.0

### PR DESCRIPTION
**Pull request by Proxyer**
Hello, author.
I updated the Japanese translation. Please confirm and merge. Thank you.

### CODE REVIEW

**Comment by user19990313** [comment]
Hello Proxyer,
Thanks for your hard work, but this file should be updated again:
RuntimeGC/Languages/Japanese/Keyed/HelpContents2.xml
Please compare it with RuntimeGC/Languages/English/Keyed/HelpContents2.xml, one key in this file has been rewritten(<HelpTextQB />)

Once this file is correctly updated, I will merge this PR.
Plus: Can you also translate the file RuntimeGC.SteamWorkshopDescription.1.0.txt? This is for Steam Workshop description; the current Japanese description is outdated and lacks format tags. Please do not remove [b][i][/u][url=...] these kind of tags.

**Comment by Proxyer** [comment]
Thank you for checked. ok I will.

**Comment by user19990313** [comment]
Oh one more thing:
Please run the game and make sure the texts are within button range. If they exceed, consider shorten them.

**Comment by user19990313** [comment]
Seriously, your latest commit is an English translation file.
Please make sure everything is correct and completed before committing.

**Comment by Proxyer** [comment]
Thank you marge! Continue checking the description of the workshop page.

**Comment by user19990313** [comment]
1. HelpContent2.xml is still in English; you didn't translate it
2. Put Steam Workshop description in a new txt file and attach it in your comment; do not modify the origional txt or other translators will have no templates.

**Comment by Proxyer** [comment]
hmm other part? sorry.

**Comment by Proxyer** [comment]
It was a perfect mistake. I was uploading the original file for comparison. I truly am sorry. I replaced it.

**Comment by user19990313** [comment]
I'm merging this PR. Also you can provide translated workshop text.

**Comment by Proxyer** [comment]
Yes! but now AM 0:47 in Japan.. I'm sorry, but I'm going to bed. The explanation of the workshop is on the way of work but will continue tomorrow. Thank you!see you later.

**Pull request merged**
